level = "debug"          # 日志等级 debug info warn error
stacktrace = true        # 默认为true 在error级别及以上显示堆栈
addCaller = true         # 默认为true 增加调用者信息
callerShip = 1           # 默认为3 调用栈深度
mode = "console"         # 默认为console 输出到控制台 console file
json = false             # 默认为false 是否json格式化
fileName = ""            # 可选 file模式参数 输出到指定文件
errorFileName = ""       # 可选 file模式参数 错误日志输出到的地方
maxSize = 0              # 可选 file模式参数 文件大小限制 单位MB
maxAge = 0               # 可选 file模式参数 文件最大保存时间 单位天
maxBackup = 0            # 可选 file模式参数 最大的日志数量
async = false            # 默认为false file模式参数 是否异步落盘
compress = false         # 默认为false file模式参数 是否压缩
console = false          # 默认为false file模式参数 是否同时输出到控制台
color = true             # 默认为false 输出是否彩色 在开发的时候推荐使用
port = 34569             # 是否开启http热更新日志级别